### ISSUE TITLE
Transparent bar

### ISSUE THREAD

**Issue by DmitryHudrich** [fabioluciano/tmux-tokyo-night#37]
is there a way to make the bar transparent instead of gray?

![image](https://github.com/user-attachments/assets/ec8aa898-f621-42ce-a576-ba538c10e498)

**Comment by cameronr** [comment]
I don't think there's a way to do it out of the box. I do it by defining my own palette (along with some other color tweaks):
https://github.com/cameronr/dotfiles/blob/main/tmux/tmux-tokyo-night-theme-cam.sh

Here's what it looks like:
![Screenshot 2024-09-02 at 13 01 50](https://github.com/user-attachments/assets/4b57e9fc-3c79-4c9b-bcae-9d7d7e3279f7)


As part of my tmux setup, I set it to my theme and symlink the theme file to `tmux-tokyo-night/src/palletes/cam.sh`:
https://github.com/cameronr/dotfiles/blob/fe4a29fa34e72d7d1259ac3a731d0080ebe7db31/tmux/tmux.conf#L109-L126

**Comment by DmitryHudrich** [comment]
this looks nice, but incompatible with transparent background, unfortunately

**Comment by cameronr** [comment]
Ah, I misunderstood. I don't think it's currently supported but I took a stab at it. Is this what you're looking for:

![Screenshot 2024-09-07 at 11 53 48](https://github.com/user-attachments/assets/b3af03ac-4631-4713-a5b4-6ab023f2cec5)

![Screenshot 2024-09-07 at 11 56 25](https://github.com/user-attachments/assets/0cc5461b-7308-4a3f-b07b-12681b18a601)

If yes, I can clean it up and submit a PR.

**Comment by DmitryHudrich** [comment]
Wow, thanks a lot. it really works the way it should. we need a pr

**Comment by cameronr** [comment]
Ok, I'll submit a PR. I added the code to my fork that already has a PR to fix my battery plugin, tho, so it'll have to come after that's approved.

**Comment by gnohj** [comment]
transparency still isn't working for me.. battery works though

**Comment by cameronr** [comment]
@gnohj hmm, can you post your config and a screenshot of what it looks like/what's wrong? And what terminal are you using?

**Comment by gnohj** [comment]
@cameronr Here are both configs ![Screenshot 2024-10-22 at 12 16 58](https://github.com/user-attachments/assets/c9baadeb-8b09-4893-b1b2-91807990dba8)

**Comment by cameronr** [comment]
@gnohj Since you're using that custom separator, make sure to define `theme_transparent_left_separator_inverse` and `theme_transparent_right_separator_inverse` as shown in the [docs](https://github.com/fabioluciano/tmux-tokyo-night?tab=readme-ov-file#Transparency-examples):

> set -g @theme_transparent_left_separator_inverse ''
> set -g @theme_transparent_right_separator_inverse ''

But that wouldn't stop it from working, it would just make it not look quite right. Did you make sure to update `tmux-tokyo-night`? What does this show:

`git -C ~/.tmux/plugins/tmux-tokyo-night show -s --oneline`

It should look like this:

`838106a (HEAD, tag: v1.8.0, upstream/main, upstream/HEAD) chore(release): 1.8.0 [skip ci]`

If it doesn't, try `<prefix> U`, wait a second, and enter `all` when it asks to update all plugins. Alternatively, `git -C ~/.tmux/plugins/tmux-tokyo-night pull origin main`. After either of those, rerun the version check above and make sure you have the latest code.

**Comment by gnohj** [comment]
@cameronr ahh- I was on `1.7.1`. Thanks alot!!
